#!/bin/bash

# This script will setup everything my clean install of arch linux needs.
# Configures everything as well as installs all my packages therefore serving
# as a repository of my used programs.

########################################
### AFTER ARCH BASE INSTALL COMPLETE ###
########################################

# still while root
useradd -m -g wheel infiniter
echo "Changing infiniter user password"
passwd infiniter

echo "Logging in as infiniter"
su infiniter

mkdir ~/Torrents
mkdir ~/Documents
mkdir ~/Downloads
mkdir ~/Code
mkdir ~/Clones

# installs {{{

sudo pacman -Syy
sudo pacman -S \
	alacritty \
	git \
	wget \
	neofetch \
	mpv \
	pavucontrol \
	pulseaudio \
	wl-clipboard \
	zathura \
	zathura-pdf-mupdf \
	qutebrowser \
    rsync \
    transmission-cli \
    network-manager-applet \
    tmux \
    youtube-dl

# hooks {{{
  sudo usermod -a -G transmission infiniter
  sudo usermod -a -G video infiniter
# }}}

# }}}

# git installs {{{

install_paru(){
    cd $CLONES_DIR
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si
}

install_subtube(){
    cd $CLONES_DIR
    git clone https://github.com/nagy135/subtube
    cd subtube
    echo "Installing subtube..."
    sudo make install
}

CLONES_DIR=$HOME/Clones
DOTS_DIR=$CLONES_DIR/dots

git clone https://github.com/nagy135/dots $DOTS_DIR

# mine
git clone https://github.com/nagy135/hackerrank $CLONES_DIR/hackerrank
git clone https://github.com/nagy135/pomodorust $CLONES_DIR/pomodorust
install_subtube
git clone https://github.com/nagy135/sort-rs $CLONES_DIR/sort-rs
git clone https://github.com/nagy135/rusty-type $CLONES_DIR/rusty-type
git clone https://github.com/nagy135/utils $CLONES_DIR/utils
git clone https://github.com/nagy135/dwm $CLONES_DIR/dwm
git clone https://github.com/nagy135/brain-dumps $CLONES_DIR/brain-dumps
git clone https://github.com/nagy135/3Dmodels $CLONES_DIR/3Dmodels

# other
install_paru
git clone https://github.com/nagy135/torque $CLONES_DIR/torque
git clone https://github.com/nagy135/wuzz $CLONES_DIR/wuzz
git clone https://github.com/nagy135/z.lua $CLONES_DIR/z.lua

# }}}

# AUR installs {{{

paru -Syy
paru google-chrome \
	lazygit \
	bemenu-wayland \
	nerd-fonts-mononoki \
    river \
    xob \
    subliminal \
    spotify-tui \
    htim

# }}}
