#!/bin/bash

# requires bpm (from bpm-tools) uses sox
#   requires (libao libid3tag libmad  opusfile twolame wavpack)
# requires ffpmeg

# First argument: TEMPO
# Second argument: PATH_TO_SONG

# $1 - target song
get_bpm(){
    sox $1 -t raw -r 44100 -e float -c 1 - | bpm 2> /dev/null
}

# $1 - song to convert
# $2 - tempo in decimal
change_speed(){
    original_name=$(basename $1)
    extension="${original_name##*.}"
    ffmpeg \
        -i $1 \
        -filter:a "atempo=$2" \
        "/tmp/tttt/${original_name}-changed.${extension}"
}

[ $# -lt 2 ] \
    && echo "Pass in tempo and path to song" \
    && exit 1

re='^[0-9]+$'
! [[ $1 =~ $re ]] && echo "First argument has to be number" && exit 2

target_bpm=$1
song=$2
bpm=$(get_bpm $song)
conversion=$(echo "scale=4;$target_bpm/$bpm" | bc)
change_speed $song $conversion
