#!/bin/bash

fifo=/tmp/brightness.fifo
pid_file=/tmp/brightness.pid

if [[ $1 == '-init' ]]; then
    mkfifo $fifo
    chmod 766 $fifo
    tail -f $fifo | xob -t 1000 -s brightness -m 100 &> /dev/null &
    echo $! > $pid_file
    exit 0
elif [[ $1 == '-k' ]]; then
    rm $fifo
    kill $(cat $pid_file)
    pkill -f "tail -f $fifo"
    exit 0
fi

actual=$(xbacklight -get)
step=10

[ $actual -le 10 ] && step=1
if [ $1 -gt 0 ]; then
    [ $actual -lt 10 ] && xbacklight -set 10 || xbacklight -inc 10
else
    xbacklight -dec $step
fi

echo $(xbacklight -get) > $fifo
