#!/bin/bash

PATH_FILE=/tmp/clicker

[ ! -f $PATH_FILE ] && touch $PATH_FILE

if [[ $1 == --record ]]; then
    eval $(xdotool getmouselocation --shell)
    [[ $2 == '-r' ]] \
        && RIGHT="r" \
        || RIGHT=""
    echo "$X $Y $SCREEN $RIGHT" >> $PATH_FILE
elif [[ $1 == --clear ]]; then
    > $PATH_FILE
elif [[ $1 == --perform ]]; then
    while read position; do
        x=$(echo $position | cut -d' ' -f1)
        y=$(echo $position | cut -d' ' -f2)
        screen=$(echo $position | cut -d' ' -f3)
        right=$(echo $position | cut -d' ' -f4)

        button=1
        [ $(echo "$right" | sed -n '/r$/p' | wc -l) -ne 0 ] \
            && button=3
        xdotool mousemove --screen $screen $x $y click $button
        sleep 0.1
    done < $PATH_FILE
else
    echo "unknown command"
    exit 1
fi
