#!/bin/bash

PATH_FILE=/tmp/clicker

[ ! -f $PATH_FILE ] && touch $PATH_FILE

if [[ $1 == --record ]]; then
    eval $(xdotool getmouselocation --shell)
    echo "$X $Y $SCREEN" >> $PATH_FILE
elif [[ $1 == --clear ]]; then
    > $PATH_FILE
elif [[ $1 == --perform ]]; then
    while read position; do
        echo pos $position
        x=$(echo $position | cut -d' ' -f1)
        y=$(echo $position | cut -d' ' -f2)
        screen=$(echo $position | cut -d' ' -f3)
        xdotool mousemove --screen $screen $x $y click 1
        sleep 0.1
    done < $PATH_FILE
else
    echo "unknown command"
    exit 1
fi
