#!/bin/bash

declare -A arr

  arr['black']='#0b0b0b'
    arr['red']='#c22330'
  arr['green']='#19a85b'
 arr['yellow']='#f9dc2b'
   arr['blue']='#304bcc'
arr['magenta']='#d13273'
   arr['cyan']='#2dc189'
  arr['white']='#b2d3d9'

FUZZEL="fuzzel -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d"

choice=$(echo "${!arr[@]}" | tr ' ' '\n' | $FUZZEL -P "Pick color: ")
[[ ! -z $choice ]] && echo ${arr[$choice]} | tr -d '\n' | wl-copy
