#!/bin/sh

GREEN=$'\e[1;32m'
YELLOW=$'\e[1;33m'
RED=$'\e[1;31m'
BLUE=$'\e[1;34m'
END=$'\e[0m'

lines=$(docker-compose ps --services)
[ $? -gt 0 ] && exit 1

choice=$(echo "$lines" | fzf -e)
[[ -z $choice ]] && exit 0

case $1 in
    logs|-l|--logs)
        tail_lines=300
        [ -n "$2" ] && tail_lines=$2
        echo "${GREEN}running:${END} ${YELLOW}docker-compose ${BLUE}logs${END} ${YELLOW}-t -f --tail $tail_lines${END} ${RED}$choice${END} ${BLUE}bash${END}"
        docker-compose logs -t -f --tail $tail_lines $choice
        ;;
    *)
        echo "${GREEN}running:${END} ${YELLOW}docker-compose ${BLUE}exec${END} ${RED}$choice${END} ${BLUE}bash${END}"
        docker-compose exec $choice bash \
            || docker-compose exec $choice sh
        ;;
esac

