#!/bin/bash

TERMINAL=alacritty
CLASS_FLAG="--class"
EXECUTE_FLAG="-e"

CLASSNAME=plain_dropdown
[[ $1 == 'python' ]] && CLASSNAME=python_dropdown

instance=$(xdotool search --classname $CLASSNAME)

# if not running, just open
[[ $instance == '' ]] \
    && [[ $1 == 'python' ]] \
    && ($TERMINAL $CLASS_FLAG $CLASSNAME $EXECUTE_FLAG python &> /dev/null &) \
    && exit

[[ $instance == '' ]] \
    && ($TERMINAL $CLASS_FLAG $CLASSNAME &> /dev/null &) \
    && exit

# else, toggle shown/hidden
[[ $(xprop -id $instance | grep WM_STATE_HIDDEN) != '' ]] \
    && bspc node $instance -g hidden=on \ # hide it
    && exit

# or show it
bspc node $instance -g hidden=off
bspc node $instance -d $(bspc query -D -d focused)
bspc node $instance -f
