#!/bin/bash

declare -A projects

# CREDENTIALS {{{

projects["project"]=$(cat << EOM
user@host
3337
db-user
db-name
db-password
EOM
)


# }}} CREDENTIALS

choice=$(echo ${!projects[@]} | tr ' ' '\n' | fzf)
[ -z $choice ] && echo "nothing chosen...exiting" && exit 1

lines="${projects[$choice]}"

location=$(echo "$lines" | sed -n '1p')
port=$(echo "$lines" | sed -n '2p')
user=$(echo "$lines" | sed -n '3p')
db=$(echo "$lines" | sed -n '4p')
pass=$(echo "$lines" | sed -n '5p')

bridge_port="3333"
socket_file="/tmp/db-backup-socket"

ssh -L \
    "${bridge_port}:127.0.0.1:${port}" \
    -M \
    -S "$socket_file" \
    -fNT "$location"

stamp=$(date "+%Y.%m.%d-%H.%M.%S")

export PGPASSWORD="$pass"
pg_dump \
    -p "$bridge_port" \
    -h localhost \
    -U "$user" \
    -d "$db" \
    --file="${HOME}/${db}-${stamp}.sql" \
    --column-inserts

ssh \
    -S "$socket_file" \
    -O exit "$location"

