#!/bin/bash

[[ -z $1 ]] && notify-send "Filer" "no argument provided" && exit 1

OPEN_IN_TERMINAL="foot --working-directory"
FUZZEL="fuzzel -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d -w 70"

sufix=""
[[ $2 == "clip" ]] && sufix=" (clipboard)"

chosen=$(ls $1 | $FUZZEL -P "Filer${sufix}: ")
[[ -z $chosen ]] && exit

chosen=$(echo "$1/$chosen" | tr -d '\n')

[[ $2 == "clip" ]] \
    && (echo -n $chosen | wl-copy) \
    && exit

case "$chosen" in
    *.jpg | *.png ) 
        sxiv $chosen
        ;;
    *.pdf ) 
        zathura $chosen &> /dev/null
        ;;
    *)
        notify-send "Filer" "unrecognized file format, opening terminal in directory..."
        $OPEN_IN_TERMINAL $(dirname $chosen) #  TODO: maybe recursive choices?
        ;;
esac
