#!/bin/bash

LSBLK_STREAM=$(lsblk --noheadings --raw)

mount_unmount=$(echo -e "mount\nunmount" | rofi -theme "/home/infiniter/.config/rofi/tmux.rasi" -dmenu -i -p 'Mount or Unmount?')
DIRECTION=0
[[ $mount_unmount == 'mount' ]] && DIRECTION=1

[ $DIRECTION -eq 1 ] \
    && PARTITIONS=$(echo "$LSBLK_STREAM" | awk '$2~/[[:digit:]]:[^0]/ && $7==""') \
    || PARTITIONS=$(echo "$LSBLK_STREAM" | awk '$2~/[[:digit:]]:[^0]/ && $7!=""')

[ $DIRECTION -eq 1 ] \
    && DEVICE=$(echo -e "$PARTITIONS" | awk '{print $1 " - " $4}' | rofi -theme "/home/infiniter/.config/rofi/tmux.rasi" -dmenu -i -p 'Select partition') \
    || DEVICE=$(echo -e "$PARTITIONS" | awk '{print $1 " - " $4 " - " $7}' | rofi -theme "/home/infiniter/.config/rofi/tmux.rasi" -dmenu -i -p 'Select partition')

# [[ -z $DEVICE ]] && exit 0

# echo $DEVICE

# mkdir /mnt/$DEVICE

# mount /dev/$DEVICE /mnt/$DEVICE || unmount /dev/$DEVICE
