#!/bin/bash

HISTORY="/home/infiniter/.local/share/qutebrowser/mpv_history"

if [[ $1 == '--clear' ]]; then
    echo -n "" > $HISTORY
    notify-send -u critical -t 1500 "MPV history" "ARE YOU SURE??? uncomment this line in mpv_history script"
    exit 0
fi

if [[ $(cat $HISTORY | wc -l) -eq 0 ]]; then
    notify-send -t 1500 "MPV history" "Empty"
    exit 0
fi

# remove those that have no title
sed -i "/^(/d" $HISTORY

# remove duplicates by mi utility binary (https://github.com/nagy135/utils/tree/master/uniquer)
uniquer $HISTORY

if [[ $1 == '--clipboard' ]] || [[ $1 == '--qutebrowser' ]]; then
    type=$(echo $1 | tr -d '-')
    chosen=$(tac $HISTORY | bemenu -l 10 -i -p "MPV history - $type")
else
    chosen=$(tac $HISTORY | sed 's/\s-\sYouTube(.*//' | sed 's/([^)]*)$//'| bemenu -l 10 -i -p 'MPV history' --tf "#19a85b" --hf "#19a85b")
    signal=$?
    if [[ $chosen == '' ]]; then
        exit 1
    fi
    chosen=$(cat $HISTORY | grep "$chosen" | head -n 1)

    echo $chosen >> $HISTORY
fi

if [[ $chosen == '' ]]; then
    exit 1
else
    url=$(echo $chosen | awk -F "(" '{print $NF}' | sed 's/.$//')


    if [[ $1 == '--clipboard' ]]; then
        echo $url | wl-copy
        notify-send -i 'none' "Clipboard content" "$url"
    elif [[ $1 == '--qutebrowser' ]]; then
        qutebrowser $url
    elif [[ $1 == '--chrome' ]]; then
        google-chrome-stable $url
    else
        if [[ $(echo $url | sed '/.*\(twitch\.tv\).*/d' | wc -l) -eq 0 ]]; then
            mpv $url
            if [[ $? -gt 0 ]]; then
                notify-send -i 'none' -t 2000 "Twitch" "Could not play stream"
            fi
        else
            # youtube-viewer --no-interactive --player=mpv --resolution=720p "$url"
            mpv $url
        fi
    fi
fi
