#!/bin/bash

HISTORY="/home/infiniter/.local/share/qutebrowser/mpv_history"
SEPARATOR="##@@##@@##"

FUZZEL="fuzzel -l 25 -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d -w 70"

if [[ $1 == '--clear' ]]; then
    backup=/tmp/mpv_history.backup
    cp $HISTORY $backup
    echo -n "" > $HISTORY
    notify-send -u critical -t 1500 "MPV history" "cleared all records (moved them to $backup)"
    exit 0
fi

if [[ $(cat $HISTORY | wc -l) -eq 0 ]]; then
    notify-send -t 1500 "MPV history" "Empty"
    exit 0
fi

if [[ $1 == '--qutebrowser' ]]; then
    type=$(echo $1 | tr -d '-' | tr '[:lower:]' '[:upper:]')
    prompt="$type  "
elif [[ $1 == '--clipboard' ]]; then
    type=$(echo $1 | tr -d '-' | tr '[:lower:]' '[:upper:]')
    prompt="$type  "
elif [[ $1 == '--chrome' ]]; then
    type=$(echo $1 | tr -d '-' | tr '[:lower:]' '[:upper:]')
    prompt="$type  "
else
    prompt="HISTORY  "

fi
chosen=$(tac $HISTORY | sed "s/\s$SEPARATOR.*//" | $FUZZEL -P "$prompt: ")

[[ $chosen == '' ]] && exit 1
chosen=$(cat $HISTORY | grep "$chosen" | head -n 1)

title=$(echo $chosen | sed "s/\s$SEPARATOR.*//")
url=$(echo $chosen | sed "s/.*\($SEPARATOR\)\s//")

if [[ $1 == '--clipboard' ]]; then
    echo "$url" | wl-copy
    notify-send -i 'none' "Clipboard content" "$url"

    exit 0
elif [[ $1 == '--qutebrowser' ]]; then
    qutebrowser "$url"
elif [[ $1 == '--chrome' ]]; then
    google-chrome-stable "$url"
else
    mpv "$url"
fi
cat $HISTORY | awk -vLine="$chosen" '!index($0,Line)' > /tmp/history
cat /tmp/history > $HISTORY
echo "$chosen" >> $HISTORY
