#!/bin/bash

# TYPE='spt'
TYPE='spotify'
DESKTOP=10

if [[ ! $(pidof $TYPE) ]]; then
    bspc desktop -f $DESKTOP
    [ $TYPE == 'spt' ] && alacritty -e spt &> /dev/null &
    [ $TYPE == 'spotify' ] && spotify &
else
    bspc desktop -f $DESKTOP
fi
