#!/bin/sh
PID_FILE=/tmp/redshift_pid

[[ $1 -lt 0 ]] && kill $(cat $PID_FILE)  && rm $PID_FILE
[[ $1 -lt 0 ]] && exit 0

value=$(rofi -theme "~/.config/rofi/input.rasi" -dmenu -i -p "Temp" < /dev/null)

[ -z "$value" ] && exit 0

[[ -f $PID_FILE ]] \
    && kill $(cat $PID_FILE) \
    && rm $PID_FILE

gammastep -P -O $value &
echo -n "$!" > $PID_FILE
