#!/bin/sh

value=0
if [[ $1 == "-init" ]]; then
    echo "6000" > /tmp/current_redshift
    value=6000
elif [[ $1 == '-day' ]] || [[ $1 == 'day' ]]; then
    actual=6000
    echo "$actual" > /tmp/current_redshift
    value=$actual
elif [[ $1 == '-night' ]] || [[ $1 == 'night' ]]; then
    actual=2200
    echo "$actual" > /tmp/current_redshift
    value=$actual
else
    if [[ $1 -gt 0 ]]; then
        actual=$(cat /tmp/current_redshift)
        actual=$(($actual+200))
        if [[ $actual -gt 6000 ]]; then
            actual=6000
        fi
        echo "$actual" > /tmp/current_redshift
        value=$actual
    elif [[ $1 -lt 0 ]]; then
        actual=$(cat /tmp/current_redshift)
        actual=$(($actual-200))
        if [[ $actual -lt 0 ]]; then
            actual=0
        fi
        echo "$actual" > /tmp/current_redshift
        value=$actual
    fi
fi
gammastep -P -O $value
