#!/bin/sh

if [[ $1 == '-zone' ]]; then
    grim -g "$(slurp)" - | wl-copy -t image/png
elif [[ $1 == '-save' ]]; then
    grim ~/screenshot_$(date '+%Y-%m-%d_%H:%M').png
else
    grim - | wl-copy -t image/png
fi
