#!/bin/bash

GREEN=$'\e[1;32m'
YELLOW=$'\e[1;33m'
RED=$'\e[1;31m'
BLUE=$'\e[1;34m'
END=$'\e[0m'

colorize(){
    echo "$1${END}" | sed "s/^/${RED}/ ; s/@/${END}@${YELLOW}/"
}

directory="$(dirname "$(realpath "$0")")"
source $directory/resources/connections

CLIP=0
case $1 in
    --clip | -c)
        CLIP=1
        ;;
esac

choice=$(echo "$conn_pairs" | cut -d ' ' -f1 | fzf --height 50%)
[ -z "$choice" ] && echo "nothing chosen, exiting..." && exit 1

target=$(echo "$conn_pairs" | awk -v choice="$choice" '{
    if ($1 == choice) {
        print $2
        exit
    }
}')

colorized=$(colorize $target)

if [ $CLIP -eq 1 ]; then
    echo -n "$target" | pbcopy
    echo "Copied to clipboard: $target"
    exit
fi

echo "${GREEN}running${END} ${BLUE}ssh${END} ${colorized}${END}"
ssh $target
