#!/bin/bash

GREEN=$'\e[1;32m'
YELLOW=$'\e[1;33m'
RED=$'\e[1;31m'
BLUE=$'\e[1;34m'
END=$'\e[0m'

colorize(){
    echo "$1${END}" | sed "s/^/${RED}/ ; s/@/${END}@${YELLOW}/"
}

directory="$(dirname "$(realpath "$0")")"
source $directory/resources/connections

SCP=0
CLIP=0
case $1 in
    --scp | -s)
        SCP=1
        ;;
    --clip | -c)
        CLIP=1
        ;;
esac

choice=$(echo "$conn_pairs" | cut -d ' ' -f1 | fzf --height 50%)
[ -z "$choice" ] && echo "nothing chosen, exiting..." && exit 1

target=$(echo "$conn_pairs" | awk -v choice="$choice" '{
    if ($1 == choice) {
        print $2
        exit
    }
}')

colorized=$(colorize $target)

# if copy to clipboard
# if [ $CLIP -eq 1 ]; then
#     echo -n ${conn_pairs[${choice}]} | xclip -sel clipboard
#     exit
# fi

# if simple connection
if [ $SCP -eq 0 ]; then
    echo "${GREEN}running${END} ${BLUE}ssh${END} ${colorized}${END}"
    ssh $target
    exit
fi

# else scp transfer
# echo "1 : local => server"
# echo "2 : server => local"
# echo -n "Direction? (write number): "
# read DIRECTION
# echo -n "From: "
# read FROM
# echo -n "To: "
# read TO
#
# [ $DIRECTION -eq 1 ] \
#     && echo "${GREEN}running${END} ${BLUE}scp -r $FROM ${colorized}:$TO${END}" \
#     || echo "${GREEN}running${END} ${BLUE}scp -r ${colorized}:$FROM $TO${END}"
#
# [ $DIRECTION -eq 1 ] \
#     && scp -r $FROM $connection:$TO \
#     || scp -r $connection:$FROM $TO
