#!/bin/sh

# NOTE: throwing away bind mode

CONFIG=~/.config/sway/config

PICKER="rofi -dmenu -i -p"

RED=$'\e[1;31m'
END=$'\e[0m'

usage(){
    echo "Usage: sway_binds <MODE>"
    echo "Searches binds or descriptions notifying the other one"
    echo ""
    echo "Modes:"
    echo "  -b, --bind                 search binds => notify description"
    echo "  -d, --description          search descriptions => notify bind"
}

[ $# -lt 1 ] && usage && exit

case $1 in
    --bind | -b)
        MODE="bind"
        ;;
    --description | -d)
        MODE="description"
        ;;
    *)
        echo "${RED}Unknown option!${END}"
        usage
        exit 1
        ;;
esac

# first prepare lines to search on
[ $MODE == "bind" ] \
    && lines=$(sed -n "/###/{n;p}" "$CONFIG" \
        | sed 's/bindsym\s//' \
        | sed 's/\$mod/Super/' \
        | cut -d' ' -f1 \
        )
[ $MODE == "description" ] \
    && lines=$(sed -n '/###/p' "$CONFIG" \
        | sed 's/^[ #]*//')

# next, select
choice=$(echo "$lines" | $PICKER "Pick $MODE: " 2> /dev/null)
[ -z "$choice" ] && exit 0

# find matching line
[ $MODE == "description" ] \
    && pair=$(sed -n "/$choice$/{n;p}" "$CONFIG"\
        | sed 's/bindsym\s//' \
        | sed 's/\$mod/Super/' \
        | cut -d' ' -f1 \
    )
[ $MODE == "bind" ] \
    && reverted=$(echo "$choice" \
        | sed 's/Super/\$mod/' \
        | sed 's/Alt/Mod1/'
    ) \
    && pair=$(sed -n "/$reverted /{x;p;d;}; x" "$CONFIG" \
        | sed 's/### //'
    )

# notify result
notify-send -t 3000 "$choice" "$pair"
