#!/bin/bash

DIRECTORY=~/Tabs
TABBER_DATA=/tmp/tabber_data

notify_user() {
    osascript -e "display notification \"$2\" with title \"$1\""
}

if [[ $1 == "process" ]]; then
    subdir=""
    per_page=4
    
    if [ -n "$2" ]; then
        if [ -d "$DIRECTORY/$2" ]; then
            subdir=$2
            per_page=${3:-4}
        else
            per_page=$2
            if [ -f "$TABBER_DATA" ]; then
                subdir=$(cat "$TABBER_DATA")
            else
                subdir=$(osascript -e 'tell application "System Events" to display dialog "Tabs directory name:" default answer ""' -e 'text returned of result' 2>/dev/null)
                [ -z "$subdir" ] && exit 0
            fi
        fi
    else
        if [ -f "$TABBER_DATA" ]; then
            subdir=$(cat "$TABBER_DATA")
        else
            subdir=$(osascript -e 'tell application "System Events" to display dialog "Tabs directory name:" default answer ""' -e 'text returned of result' 2>/dev/null)
            [ -z "$subdir" ] && exit 0
        fi
    fi
    
    files=$(ls "$DIRECTORY/$subdir"/*.png 2>/dev/null | wc -l)
    [ $files -eq 0 ] && notify_user "Tabber" "No images in $subdir!" && exit 1
    
    mkdir -p "$DIRECTORY/$subdir/pages"
    array=()
    i=0
    page=1
    
    for file in $(ls -1 "$DIRECTORY/$subdir"/*.png | sort -V); do
        i=$((i+1))
        if [ $i -gt $per_page ]; then
            i=1
            if [ ${#array[@]} -gt 0 ]; then
                magick convert -append -resize 1200x "${array[@]}" "$DIRECTORY/$subdir/pages/output-$page.png"
            fi
            page=$((page+1))
            array=()
        fi
        array+=("$file")
    done
    
    if [ ${#array[@]} -gt 0 ]; then
        magick convert -append -resize 1200x "${array[@]}" "$DIRECTORY/$subdir/pages/output-$page.png"
    fi
    
    rm -f "$TABBER_DATA"
    notify_user "Tabber" "Done! $per_page per page"

else
    if [ ! -f "$TABBER_DATA" ]; then
        subdir=$(osascript -e 'tell application "System Events" to display dialog "Tabs directory name:" default answer ""' -e 'text returned of result' 2>/dev/null)
        [ -z "$subdir" ] && exit 0
        mkdir -p "$DIRECTORY/$subdir"
        echo "$subdir" > "$TABBER_DATA"
    fi
    
    subdir=$(cat "$TABBER_DATA")
    count=$(ls "$DIRECTORY/$subdir"/*.png 2>/dev/null | wc -l)
    order=$((count+1))
    
    /usr/sbin/screencapture -i "$DIRECTORY/$subdir/$order.png" 2>/dev/null || exit 0
    
    if [ -f "$DIRECTORY/$subdir/$order.png" ]; then
        notify_user "Tabber" "Captured ($order)"
    fi
fi
