#!/bin/bash

DIRECTORY=~/Documents/Tabs
TMP_TAB=/tmp/tabber.png
MULTIPLE_DATA=/tmp/tabber_multiple_data
FUZZEL="fuzzel -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d -w 40"

if [[ $1 == "process" ]]; then
    [ ! -f $MULTIPLE_DATA ] && notify-send "Tabber" "set multiple data first!" && exit 1
    subdirectory=$(cat $MULTIPLE_DATA | sed -n '2p')
    height=$(cat $MULTIPLE_DATA | sed -n '1p' | sed 's/[^x]*x//')
    per_page=$((1920/$height))
    total=$(ls $DIRECTORY/$subdirectory | wc -l)

    # joining of pieces
    mkdir -p $DIRECTORY/$subdirectory/pages
    array=()
    i=0
    page=1
    for file_i in $(seq 1 $total); do
        i=$((i+1))
        if [ $i -ge $per_page ]; then
            i=1

            convert -append ${array[@]} $DIRECTORY/$subdirectory/pages/output-$page.png

            page=$((page+1))
            array=()
        fi
        array+=" $DIRECTORY/$subdirectory/${file_i}.png"
    done

    # last incomplete page
    if [[ ${#array[@]} -gt 0 ]]; then
        convert -append ${array[@]} $DIRECTORY/$subdirectory/pages/output-$page.png
    fi
    rm $MULTIPLE_DATA
elif [[ $1 == "grab" ]]; then
    [ ! -f $MULTIPLE_DATA ] && notify-send "Tabber" "set multiple data first!" && exit 1
    geometry=$(cat $MULTIPLE_DATA | sed -n '1p')
    subdirectory=$(cat $MULTIPLE_DATA | sed -n '2p')
    order=$(ls $DIRECTORY/$subdirectory | wc -l)
    order=$((order+1))
    grim -g "$geometry" $DIRECTORY/$subdirectory/$order.png
    notify-send -i 'none' -t 300 "Tabber" "piece captured"
else
    choice=$(echo -e "single\nmultiple" | $FUZZEL -l 2)
    [ -z $choice ] && exit 0

    if [[ $choice == "single" ]]; then
        slop=$(slurp -f "%x %y %w %h")
        read -r X Y W H < <(echo $slop)
        grim -g "${X},${Y} ${W}x${H}" $TMP_TAB
        if [[ -f $TMP_TAB ]]; then
            name=$(echo "" | $FUZZEL -l 0 -P 'Name this tab image: ')
            [[ ! -z $name ]] && mv $TMP_TAB $DIRECTORY/$name.png && notify-send -t 2000 -i none "TABBER" "tab saved as $DIRECTORY/$name.png"
        fi
    else
        slop=$(slurp -f "%x %y %w %h")
        read -r X Y W H < <(echo $slop)
        subdirectory=$(echo "" | $FUZZEL -l 0 -P 'Name directory for this tab: ')
        [ -z $subdirectory ] && exit 0

        mkdir $DIRECTORY/$subdirectory
        echo -e "${X},${Y} ${W}x${H}\n${subdirectory}" > $MULTIPLE_DATA
    fi
fi
