#!/bin/sh

POLYBAR_CONFIG=~/.config/polybar/config
THEMES=~/.scripts/resources/themes


theme=$(ls -1 $THEMES | rofi -dmenu -i -p "pick theme")
[ -z $theme ] && exit

main_color=$(cat $THEMES/$theme | sed -n '1p')
secondary_color=$(cat $THEMES/$theme | sed -n '2p')

sed -i "s/main-color=.*/main-color=${main_color}/" $POLYBAR_CONFIG
sed -i "s/secondary-color=.*/secondary-color=${secondary_color}/" $POLYBAR_CONFIG
