#!/bin/bash

ICON="~/.scripts/resources/tmux.png"

if [[ $1 == 'kill' ]]; then
    chosen=$(tmux ls | awk -F: '{print $1}' | fuzzel -d -P 'Kill tmux session: ')
    [[ ! -z $chosen ]] && notify-send -i $ICON -t 2000 "Tmux session killed" && foot tmux kill-session -t "$chosen" &> /dev/null &
    exit 0
elif [[ $1 == 'create' ]]; then
    chosen=$(echo "" | fuzzel -d -P 'Create tmux session: ')
    if [[ ! -z $chosen ]]; then
        notify-send -i $ICON -t 2000 "Created" "$chosen"
        tmux new-session -d -s $chosen
    fi
    exit 0
elif [[ $1 == "list" ]]; then
    pid=$(xdotool search --classname toggle_tmux getwindowpid)
    chosen=$(tmux ls | awk -F: '{print $1}' | fuzzel -d -P 'Switch tmux session: ')
    [[ -z $chosen ]] && exit 0
    # if [[ $pid != '' ]]; then
        tmux switch-client -t "$chosen"
    # else
    #     foot tmux -u attach -t "$chosen" &> /dev/null &
    # fi
    exit 0
else
    pid=$(xdotool search --classname toggle_tmux getwindowpid)
    if [[ $pid != '' ]]; then # its running
        wid=$(xdotool search --classname toggle_tmux)
        [[ $(xdotool getwindowfocus) -eq $wid ]] && kill $pid && notify-send -u critical -t 2000 -i $ICON "Tmux killed" && exit 0
        current_desktop=$(bspc query -D -d focused --names)
        current_desktop=$((current_desktop-1))
        wmctrl -l -p | awk '{print $2 " " $3}' | sed -n "/^$current_desktop.*/p" | awk '{print $2}' | grep -Fxq $pid && xdotool windowactivate $wid && exit 0
        bspc node $wid -d $(bspc query -D -d focused --names)
        xdotool windowactivate $wid
    else
        foot tmux -u new-session -A -s stuff &> /dev/null &
    fi
fi
