#!/bin/sh

DESKTOP=2
COMMAND="foot tmux new-session -A -s stuff"

[[ $(tmux list-clients | wc -l) -eq 0  ]] \
    && (swaymsg "workspace $DESKTOP; exec $COMMAND" &) \
    || (swaymsg "workspace $DESKTOP"&)
