#!/bin/bash

ROOT=~/Documents/gcodes
PARTITION=/dev/sda1
MOUNTPOINT=/mnt

keep_files=(
    "frame_calibration.gcode"
    "boxes_calibration.gcode"
    "benchy.gcode"
    "cart_coin_bundle.gcode"
)

SEPARATOR="#################################"

# select files to copy
chosen=$(ls -t $ROOT | rofi -dmenu -i -p -multi-select 'Choose gcode')
[[ -z $chosen ]] \
    && echo "[INFO] nothing chosen exiting..." \
    && exit 0

# check if sd present, then mount
[ ! -b $PARTITION ] \
    && echo "[ERROR] No $PARTITION plugged in" \
    && exit 0
sudo mount $PARTITION $MOUNTPOINT

if [[ $1 == "-r" ]]; then # remove all previous files
    # prepare flags to exclude these files from removing
    not_find_flags=""
    echo "[INFO] removing all gcodes from sd card except:"
    for keep_file in ${keep_files[@]}; do
        echo "    $keep_file"
        not_find_flags="$not_find_flags -not -name $keep_file"
    done
    echo $SEPARATOR

    # remove whats not to keep
    sudo find $MOUNTPOINT \
        -name "*.gcode" \
        -and $not_find_flags \
        -exec echo "[INFO] removing" {} \; \
        -exec rm {} \;
fi

echo "[INFO] transferring:"
# transfer what was chosen
while read -r chosen_file; do
    echo "    $chosen_file"
    full_path="$ROOT/$chosen_file"
    sudo cp $full_path $MOUNTPOINT
done <<< "$chosen"

# unmount
sudo umount $PARTITION

echo "[INFO] Done"
