#!/bin/bash

ROOT=~/3d/gcodes
DESTINATION="/Volumes/NO NAME 1"

keep_files=(
    "frame_calibration.gcode"
    "boxes_calibration.gcode"
    "benchy.gcode"
    "cart_coin_bundle.gcode"
)

SEPARATOR="#################################"

# select files to copy
choice=$(ls -t $ROOT | fzf -e -m)
[[ ! $? -eq 0 ]] \
    && echo "[INFO] nothing chosen exiting..." \
    && exit 0

# check if sd present, then mount
[ ! -d "$DESTINATION" ] \
    && echo "[ERROR] Plug in sd card!" \
    && exit 0

if [[ $1 == "-r" ]]; then # remove all previous files
    # prepare flags to exclude these files from removing
    echo "[INFO] removing all gcodes from sd card except:"
    for keep_file in ${keep_files[@]}; do
        echo "    $keep_file"
        not_find_flags="$not_find_flags -not -name $keep_file"
    done
    echo $SEPARATOR

    # remove whats not to keep
    sudo gfind "$DESTINATION" \
        -name "*.gcode" \
        -and $not_find_flags \
        -exec echo "[INFO] removing" {} \; \
        -exec rm {} \;
fi

echo "[INFO] transferring:"
# transfer what was chosen
while read -r chosen_file; do
    full_path="$ROOT/$chosen_file"
    sudo cp "$full_path" "$DESTINATION"
    echo "    $chosen_file"
done <<< "$choice"

diskutil unmountDisk $(diskutil list "NO NAME" | head -n 1 | cut -d ' ' -f1)

echo "[INFO] Done"
