#!/bin/bash

choices=$(tsm-seeding_rows)
[[ $choices == '' ]] && exit 1

FUZZEL="fuzzel -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -w 60 -d"

choice=$( echo "$choices" | $FUZZEL -P 'Delete torrent: ')

[[ $choice == '' ]] && exit 1

choice=$(echo $choice | awk '{print $1}')
transmission-remote -t $choice -r
