#!/bin/bash

FIFO=/tmp/volume.fifo
PID=/tmp/volume.pid
CURRENT_VOLUME=/tmp/current_volume
MUTE_VAL=$MUTE_VAL

if [[ $1 == '-init' ]]; then
    mkfifo $FIFO
    chmod 766 $FIFO
    tail -f $FIFO | xob -t 1000 -s volume -m 100 &> /dev/null &
    echo $! > $PID

    echo "50" > $CURRENT_VOLUME
    pactl set-sink-volume 0 50%
elif [[ $1 == '-k' ]]; then
    rm $FIFO
    kill $(cat $PID)
    pkill -f "tail -f $fifo"
elif [[ $1 == '-mute' ]]; then
    pactl set-sink-mute 0 toggle

    [[ ! -f $MUTE_VAL ]] \
        && cat $CURRENT_VOLUME > $MUTE_VAL \
        && exit

    cat $MUTE_VAL > $CURRENT_VOLUME
    rm $MUTE_VAL
else
    [[ ! -f $MUTE_VAL ]] \
        && current_volume=$(cat $CURRENT_VOLUME) \
        exit

    current_volume=$(cat $MUTE_VAL)
    rm $MUTE_VAL
    pactl set-sink-mute 0 toggle

    current_volume=$(($current_volume+$1))
    [[ $current_volume -le 0 ]] && current_volume=0
    echo "$current_volume" > $CURRENT_VOLUME
    echo "$current_volume" > $FIFO
    pactl set-sink-volume 0 "$current_volume%"
fi
