#!/usr/bin/env bash

VIDEODIR="$HOME/Videos"
[[ ! -e $VIDEODIR ]] && mkdir -p "$VIDEODIR"


PIDPATH="/tmp/screencast.pid"
TMP_FILE_PATH="/tmp/wf-record-path"
AUDIO_OUTPUT=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
FUZZEL="fuzzel -b 0b0b0bdd -t b2d3d9ff -s 19a85bff -S 0b0b0bff -m f9dc2bff -C 19a85bff -B 2 -d"
EXT="mp4"

if [[ ! -f "$PIDPATH" ]]; then
    TIME="$(date +%Y-%m-%d-%H-%M-%S)"
    VIDPATH="$VIDEODIR/rec-$TIME.$EXT"

    if [[ $1 == "-z" ]]; then
        SLURP_GEO="$(slurp)"
        wf-recorder --audio=$AUDIO_OUTPUT -g "$SLURP_GEO" -f "$VIDPATH" &
    else
        wf-recorder --audio=$AUDIO_OUTPUT -f "$VIDPATH" &
    fi
    echo "$!" >"$PIDPATH"
    echo "$VIDPATH" > $TMP_FILE_PATH
    notify-send -t 1000 "."
else
    PID="$(cat $PIDPATH)"
    rm "$PIDPATH"

    FILE_PATH="$(cat $TMP_FILE_PATH)"
    rm "$TMP_FILE_PATH"

    kill -SIGINT "$PID"

    new_name=$(echo "" | $FUZZEL -l 0)
    [[ -z "$new_name" ]] && rm $FILE_PATH && exit 0

    dir_name="$(dirname $FILE_PATH)"
    mv "$FILE_PATH" "$dir_name/$new_name.$EXT"
    notify-send "Renamed:" "$dir_name/$new_name.$EXT"

    notify-send "Stopped recording"
fi
