#!/usr/bin/env bash

VIDEODIR="$HOME/Videos"
[[ ! -e $VIDEODIR ]] && mkdir -p "$VIDEODIR"


PIDPATH="/tmp/screencast.pid"
AUDIO_OUTPUT=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

if [[ ! -f "$PIDPATH" ]]; then
    TIME="$(date +%Y-%m-%d-%H-%M-%S)"
    VIDPATH="$VIDEODIR/rec-$TIME.mp4"

    if [[ $1 == "-z" ]]; then
        wf-recorder --audio=$AUDIO_OUTPUT -g "$(slurp)" -f "$VIDPATH" &
    else
        wf-recorder --audio=$AUDIO_OUTPUT -f "$VIDPATH" &
    fi
    echo "$!" >"$PIDPATH"
    notify-send -t 1000 "."
else
    PID="$(cat $PIDPATH)"
    kill -SIGINT "$PID"
    rm "$PIDPATH"
    notify-send "Stopped recording"
fi
