#!/usr/bin/env bash

VIDEODIR="$HOME/Videos"
[[ ! -e $VIDEODIR ]] && mkdir -p "$VIDEODIR"

PIDPATH="/tmp/screencast.pid"

if [[ ! -f "$PIDPATH" ]]; then
    TIME="$(date +%Y-%m-%d-%H-%M-%S)"
    VIDPATH="$VIDEODIR/rec-$TIME.mp4"
    wf-recorder --audio=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -g "$(slurp)" -f "$VIDPATH" &
    echo "$!" >"$PIDPATH"
    notify-send "Started recording" "$VIDPATH"
else
    PID="$(cat $PIDPATH)"
    kill -SIGINT "$PID"
    rm "$PIDPATH"
    notify-send "Stopped recording"
fi
