#!/bin/bash

# Script to search for youtube videos
# as well as saving them in MPV_HISTORY list

QUERY="$@"
QUERY=$(rofi -dmenu -i -p "Search query" -theme input.rasi)

[[ -z "$QUERY" ]] && exit 0

results=$(youtube-dl -j "ytsearch5:$QUERY" | jq '.fulltitle, .webpage_url' | sed 'N;s/\n/ /')
chosen=$(echo "$results" | sed 's/^.// ; s/" ".*//' | rofi -dmenu -i -p "Choose video" -theme tmux.rasi)

[[ -z $chosen ]] && exit 0

url=$(echo "$results" | grep "$chosen" | sed 's/^"[^"]*" "\([^"]*\)"/\1/')

mpv "$url"

[[ -f ~/.local/share/qutebrowser/mpv_history ]] && echo "$chosen($url)" >> ~/.local/share/qutebrowser/mpv_history
