#!/bin/bash

# One row per host: names/aliases address user [user ...]
connections=$(
  cat <<'EOF'
biologia 78.47.31.136 root
swissfunds_dev|sf_dev 49.12.100.180 vnagy
swissfunds_prod|sf_prod 217.16.184.94 svycarskapujcka-new
og_dev 142.93.38.79 vnagy
og_prod 206.189.116.148 vnagy
dev 157.230.108.64 vnagy
caresee 165.22.85.171 vnagy
wishmaker 116.203.48.101 vnagy
goldguard_dev|gg_dev goldguard.bywazzupa.com vnagy
goldguard_prod|gg_prod 35.158.187.52 ubuntu
chcemauto 88.99.173.121 root
infiniter 159.89.12.44 root
nixos 91.99.204.136 infiniter root
personal_mdm_logistics|pmdm 165.227.164.205 root developer
broken_mdm_logistics|bmdm 46.101.144.33 root developer
prod_mdm_logistics|prodmdm 46.101.240.200 developer root
hetzner_mdm|hmdm|warehouse 116.203.184.95 root developer
hd+_stage_vm1 51.145.135.146 sensory-root
hd+_prod_vm1 20.71.0.53 sensory-root
hd+_prod_vm2 20.71.2.124 sensory-root
sensory-prototypes 92.205.25.49 sensory-prototypes
nixpi nixpi.tail6650cb.ts.net infiniter root
nixzero nixzero.tail6650cb.ts.net infiniter root
lk-revenue 81.2.216.138 developer
metzler_preprod_vm1 192.214.183.37 cms-app
metzler_preprod_vm2 192.214.183.87 cms-app
EOF
)

# old_nixos 49.13.139.140 infiniter root
# pi 192.168.210.165 pi
